### ISSUE TITLE
Chapter 7 loads indefinitely

### ISSUE THREAD

**Issue by ThatzMatt** [Zed-z/dragons-path-restorer#1]
Every other chapter seems to work fine, but The Dragon's Protégé is stuck in infinite loading despite all HTTP responses being 200 (304 on refreshes). I tried repeating the setup process but to no avail.

**Comment by Zed-z** [comment]
Apologies for the late reply!

From what I know, it appears to be an issue with a PreloadJS script. Some time ago I made a patch that should've fixed it. Last time I tried, it did work, but if it doesn't, please clear your browser cache and try again (that's what did it for me).

It would also help if you provided some browser console output, such as PreloadJS errors that shouldn't be happening but could be likely in your case.

**Comment by ThatzMatt** [comment]
Alright! I'll try that then. Quick question: for each comic there seem to be 3 parts, but only the first one of them is displayed/available while the other two are apparently unused HTML files without extension. Are they continuations to the comics? And if so, are there plans of implementing those correctly in the future?

**Comment by Zed-z** [comment]
Originally the comics were split into several HTML pages containing 4 comic pages each. I combined all the comic pages into singular sites for both convenience, and because the site backup I work with appears to have sites 5-8 missing for each comic (only the sites to display the pages, the pages themselves are intact).
Don't worry, you're not missing anything!

**Comment by ThatzMatt** [comment]
Awesome! Thanks for answering my question, and sorry for the trouble!

**Comment by Zed-z** [comment]
No, no, I'm thankful for you checking out this repository and I'll be glad to try and fix this problem; looking forward to any updates on your side!

**Comment by ThatzMatt** [comment]
I tried everything I could, but chapter 7 keeps failing to load while everything else does. There seem to be no console errors apart from a `GET https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css net::ERR_NAME_NOT_RESOLVED` which occurs on every page.

Everything I tried:
- Switching between two browsers (Opera GX and Chrome)
- Clearing browser data on every run of the script
- Restarting the Python script with fresh files on several occasions

Despite everything, the page always appears to be stuck in its loading animation.

**Comment by Zed-z** [comment]
I just checked myself and you're right. I'll have to do some research on why this happens; the content appears to be all there when inspecting the HTML, it just refuses to start for some reason.

**Comment by Zed-z** [comment]
A quick fix I found for now is to find `<frame id="i01" ...>` (it's in `<div class="swiper-container ...>`) via the Inspector and drag it from `<div class="comic-holder">` directly into its respective `<div class="swiper-slide ...>`. The first page becomes weirdly offset, but it forces the entire comic to start up.

Meanwhile I'll try fixing it and making it work without any trickery.

**Comment by Zed-z** [comment]
Progress update: it appears the whole site only starts playing the comic once all (32 in this case) pages declare themselves as ready. However, only 31 do for this comic.

Now, I either have to fix one of the pages not reporting as ready, or add a small workaround to only wait for 31 "ready" pages in this comic. (The amount of pages will stay intact of course.)

**Comment by Zed-z** [comment]
@ThatzMatt I've pushed a new version that hopefully fixes the problem! Please redownload the tool and run the script again!

**Comment by ThatzMatt** [comment]
It now works perfectly, thank you! There is another issue that I'm having, though it's only a small one and I'm not sure if it's only on my side. When I run the tool with css tweaks enabled, dark mode only seems to apply to a portion of the page, then it's light as soon as I scroll down. Here's an image as an example.

![immagine_2023-12-30_160215612](https://github.com/Zed-z/dragons-path-restorer/assets/77584420/4f81d68d-4926-4550-bb84-fc14c05582a8)

**Comment by Zed-z** [comment]
That is indeed a real bug. Created a new issue for that and will fix it sometime in the future, thanks!

**Comment by ThatzMatt** [comment]
Alright, thank you for your patience!
